env:
  es2021: true
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
  - sort-keys-fix
  - unused-imports
rules:
  camelcase:
    - error
    - properties: never
  curly: error
  comma-spacing:
    - error
    - before: false
      after: true
  eqeqeq: error
  eol-last:
    - error
    - always
  func-call-spacing:
    - error
    - never
  func-name-matching: error
  func-names:
    - error
    - always
  indent:
    - error
    - 2
  key-spacing:
    - error
    - beforeColon: false
  linebreak-style:
    - error
    - unix
  no-console:
    - error
    - allow: [warn, error]
  no-else-return: error
  no-empty: error
  no-extra-semi: error
  max-len:
    - error
    - code: 120
  object-curly-spacing:
    - error
    - always
  quotes:
    - error
    - single
  space-before-blocks: 2
  semi:
    - error
    - always
  sort-keys: warn
  sort-keys-fix/sort-keys-fix: warn
  unused-imports/no-unused-imports: warn
